"""Taiwan readings, by homophone.

The models are trained on mainland speech, so a word Taiwan reads differently
comes out in the mainland reading: 垃圾 as lā jī, not lè sè; 企業 as qǐ yè, not
qì yè. No model here takes a phonetic hint reliably, but every one reads an
ordinary character reliably, so the word is rewritten with a stand-in that has
the Taiwan reading and no other — 垃圾 becomes 乐色, 企业 becomes 气业. The
model is asked to say a nonsense word, and says it correctly.

The table (``taiwan_readings.tsv``) is generated by ``scripts/taiwan_readings.py``
from the McBopomofo dictionary and keyed by the Simplified form, so this pass
runs after script conversion. It is a Chinese rewrite: the locale runs it, so
Japanese — which shares glyphs with the keys (研究) and none of the readings —
never meets it.

It is keyed by *words* and looked up in text that is not segmented, so a match
is not yet evidence that the span is a word in that sentence.
``boundary_words.tsv``, from the same generator, is what settles it: each edge
of a match is offered to its neighbour, and the more common word keeps the
character. Without that, `在为` matched across `正在 | 为你` and the model read
wéi where the sentence says wèi.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import resources


def _read_table(name: str) -> dict[str, str]:
    words: dict[str, str] = {}
    text = resources.files(__package__).joinpath(name).read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("#") or not line.strip():
            continue
        word, standin, *_ = line.split("\t")
        words[word] = standin
    return words


@lru_cache(maxsize=1)
def _table() -> tuple[dict[str, str], int]:
    words = _read_table("taiwan_readings.tsv")
    return words, max(map(len, words), default=0)


@lru_cache(maxsize=1)
def standins() -> dict[str, str]:
    """Stand-ins for polyphones a model may misread — `standins.tsv`.

    Not a Taiwan difference and not applied to every model: a word is
    respelled only for a model whose catalog entry declares it misreads it
    (`ModelSpec.misreads`). This table only says what to respell it as.
    """
    return _read_table("standins.tsv")


@lru_cache(maxsize=1)
def _boundaries() -> dict[str, int]:
    """Words the substituter arbitrates against, with their corpus counts."""
    words: dict[str, int] = {}
    text = (
        resources.files(__package__)
        .joinpath("boundary_words.tsv")
        .read_text(encoding="utf-8")
    )
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        word, count = line.split("\t")
        words[word] = int(count)
    return words


def _straddles(text: str, start: int, end: int) -> bool:
    """Whether a neighbouring word has the better claim on an edge character.

    The table is keyed by words and the text it is looked up in is not
    segmented, so a match is not yet evidence that the span is a word *here*.
    `在为` is an entry, and `正在为你查詢` contains those two characters in a
    row — but the 在 belongs to 正在, and substituting had the model read
    wéi where the sentence says wèi.

    So each edge is offered to its neighbour: if the character before the
    match forms a word with the match's first character, or the character
    after forms one with its last, and that word is at least as common as the
    match itself, the match loses. Comparing counts is what keeps 不中用 —
    中用 is a word, but a rarer one than 不中, so it does not take the 中.

    Erring towards refusing is deliberate and is the reason a simple test is
    enough: a refused rewrite leaves the mainland reading, which is
    understood, while a wrong one says a different word.
    """
    known = _boundaries()
    mine = known.get(text[start:end], 0)
    before = text[start - 1 : start + 1] if start else ""
    after = text[end - 1 : end + 1]
    for neighbour in (before, after):
        if len(neighbour) == 2 and known.get(neighbour, -1) >= mine:
            return True
    return False


def taiwan_readings(text: str) -> list[tuple[str, str]]:
    """Return the (word, stand-in) rewrites the text would get, in order."""
    return _substitute(text)[1]


def apply_taiwan_readings(text: str) -> str:
    """Rewrite every table word in the text with its stand-in."""
    return _substitute(text)[0]


def apply_standins(text: str, misread: tuple[str, ...]) -> str:
    """Respell the words in `misread` with their stand-ins.

    Raises:
        KeyError: A word has no stand-in in `standins.tsv`.
    """
    return _substitute(text, _chosen(misread))[0]


def standins_for(text: str, misread: tuple[str, ...]) -> list[tuple[str, str]]:
    """Return the (word, stand-in) rewrites `apply_standins` would make."""
    return _substitute(text, _chosen(misread))[1]


def _chosen(misread: tuple[str, ...]) -> tuple[dict[str, str], int]:
    table = standins()
    words = {word: table[word] for word in misread}
    return words, max(map(len, words), default=0)


def _substitute(
    text: str, table: tuple[dict[str, str], int] | None = None
) -> tuple[str, list[tuple[str, str]]]:
    words, longest = _table() if table is None else table
    out: list[str] = []
    rewrites: list[tuple[str, str]] = []
    i = 0
    while i < len(text):
        # Longest match first: 研究所 before 研究.
        for size in range(min(longest, len(text) - i), 1, -1):
            candidate = text[i : i + size]
            standin = words.get(candidate)
            if standin is not None and not _straddles(text, i, i + size):
                out.append(standin)
                rewrites.append((candidate, standin))
                i += size
                break
        else:
            out.append(text[i])
            i += 1
    return "".join(out), rewrites
