"""Taiwan readings, by homophone.

The models are trained on mainland speech, so a word Taiwan reads differently
comes out in the mainland reading: 垃圾 as lā jī, not lè sè; 企業 as qǐ yè, not
qì yè. No model here takes a phonetic hint reliably, but every one reads an
ordinary character reliably, so the word is rewritten with a stand-in that has
the Taiwan reading and no other — 垃圾 becomes 乐色, 企业 becomes 气业. The
model is asked to say a nonsense word, and says it correctly.

The table (``taiwan_readings.tsv``) is generated by ``scripts/taiwan_readings.py``
from the McBopomofo dictionary and keyed by the Simplified form, so this pass
runs after script conversion. It is a Chinese rewrite: the locale runs it, so
Japanese — which shares glyphs with the keys (研究) and none of the readings —
never meets it.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import resources


@lru_cache(maxsize=1)
def _table() -> tuple[dict[str, str], int]:
    words: dict[str, str] = {}
    text = (
        resources.files(__package__)
        .joinpath("taiwan_readings.tsv")
        .read_text(encoding="utf-8")
    )
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        word, standin, *_ = line.split("\t")
        words[word] = standin
    return words, max(map(len, words), default=0)


def taiwan_readings(text: str) -> list[tuple[str, str]]:
    """Return the (word, stand-in) rewrites the text would get, in order."""
    return _substitute(text)[1]


def apply_taiwan_readings(text: str) -> str:
    """Rewrite every table word in the text with its stand-in."""
    return _substitute(text)[0]


def _substitute(text: str) -> tuple[str, list[tuple[str, str]]]:
    words, longest = _table()
    out: list[str] = []
    rewrites: list[tuple[str, str]] = []
    i = 0
    while i < len(text):
        # Longest match first: 研究所 before 研究.
        for size in range(min(longest, len(text) - i), 1, -1):
            candidate = text[i : i + size]
            standin = words.get(candidate)
            if standin is not None:
                out.append(standin)
                rewrites.append((candidate, standin))
                i += size
                break
        else:
            out.append(text[i])
            i += 1
    return "".join(out), rewrites
